spring:
  kafka:
    producer:
      bootstrap-servers: kafka:29092
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  main:
    allow-bean-definition-overriding: true
auto:
  create:
    topics:
      enable: 'true'
order:
  topic:
    name: ORDER-TOPIC
server:
  port: '9090'



