spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb
  main:
    allow-bean-definition-overriding: true
auto:
  create:
    topics:
      enable: 'true'
order:
  topic:
    name: order-topic
server:
  port: '9090'



