spring:
  application:
    name: my-spring-boot-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: kafka:9092

  data:
    mongodb:
      uri: mongodb://mongo:27017/testdb
      database: testdb

my-spring-boot-app:
  kafka:
    topic: ${SPRING_KAFKA_TOPIC:ORDER_TOPIC}
server:
  port: 9090
